---
- import_tasks: rhel_7.yml
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7"

- import_tasks: ubuntu_16+.yml
  when: 
  - ansible_distribution == 'Ubuntu'
  - "{{ ansible_distribution_version | version_compare('16.04', '>=') }}"
...
